# Generated by Django 5.2.12 on 2026-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factorio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
