# Generated by Django 5.2.12 on 2026-09-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factorio_app', '0002_comment_gif_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gif_url',
        ),
    ]
